
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package com.comp3652.smpl.lang;

/** CUP generated interface containing symbol constants. */
public interface Symbol {
  /* terminals */
  public static final int MOD = 15;
  public static final int PLUS = 11;
  public static final int RBRACE = 9;
  public static final int RPAREN = 6;
  public static final int SEMI = 10;
  public static final int IN = 4;
  public static final int VARIABLE = 18;
  public static final int LPAREN = 5;
  public static final int LBRACE = 8;
  public static final int COMMA = 7;
  public static final int EOF = 0;
  public static final int DEF = 2;
  public static final int DIV = 14;
  public static final int MINUS = 12;
  public static final int error = 1;
  public static final int LET = 3;
  public static final int ASSIGN = 16;
  public static final int INTEGER = 17;
  public static final int MUL = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "LET",
  "IN",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "INTEGER",
  "VARIABLE"
  };
}

