
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package com.comp3652.lang;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int IFEQUIVALENT = 25;
  public static final int SUBSTRING = 28;
  public static final int STRING_LITERAL = 49;
  public static final int LBRACKET = 10;
  public static final int CHAR = 45;
  public static final int READINT = 34;
  public static final int IFPAIR = 5;
  public static final int CASE = 35;
  public static final int CAR = 29;
  public static final int INTEGER = 41;
  public static final int CDR = 30;
  public static final int LPAREN = 12;
  public static final int SEMI = 17;
  public static final int HEX = 43;
  public static final int PRINTLN = 32;
  public static final int MINUS = 20;
  public static final int CMP = 36;
  public static final int RPAREN = 13;
  public static final int FRACTION = 44;
  public static final int COMMA = 14;
  public static final int LAZY = 4;
  public static final int CALL = 7;
  public static final int DIV = 21;
  public static final int PLUS = 19;
  public static final int IF = 37;
  public static final int ASSIGN = 9;
  public static final int EOF = 0;
  public static final int RBRACKET = 11;
  public static final int TRUE = 46;
  public static final int SIZE = 24;
  public static final int error = 1;
  public static final int MOD = 22;
  public static final int PAIR = 6;
  public static final int TIMES = 23;
  public static final int COLON = 18;
  public static final int BIN = 42;
  public static final int ELSE = 39;
  public static final int LBRACE = 15;
  public static final int BE = 8;
  public static final int READ = 33;
  public static final int LIST = 27;
  public static final int LET = 40;
  public static final int THEN = 38;
  public static final int RBRACE = 16;
  public static final int IFEQUAL = 26;
  public static final int PROC = 3;
  public static final int DEF = 2;
  public static final int FALSE = 47;
  public static final int VAR = 48;
  public static final int PRINT = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "PROC",
  "LAZY",
  "IFPAIR",
  "PAIR",
  "CALL",
  "BE",
  "ASSIGN",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "COLON",
  "PLUS",
  "MINUS",
  "DIV",
  "MOD",
  "TIMES",
  "SIZE",
  "IFEQUIVALENT",
  "IFEQUAL",
  "LIST",
  "SUBSTRING",
  "CAR",
  "CDR",
  "PRINT",
  "PRINTLN",
  "READ",
  "READINT",
  "CASE",
  "CMP",
  "IF",
  "THEN",
  "ELSE",
  "LET",
  "INTEGER",
  "BIN",
  "HEX",
  "FRACTION",
  "CHAR",
  "TRUE",
  "FALSE",
  "VAR",
  "STRING_LITERAL"
  };
}

