
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 29 14:54:40 EST 2015
//----------------------------------------------------

package com.comp3652.lang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IFEQUIVALENT = 25;
  public static final int SUBSTRING = 28;
  public static final int LBRACKET = 10;
  public static final int CHAR = 49;
  public static final int READINT = 34;
  public static final int IFPAIR = 5;
  public static final int CASE = 35;
  public static final int CAR = 29;
  public static final int INTEGER = 44;
  public static final int CDR = 30;
  public static final int LPAREN = 12;
  public static final int SEMI = 17;
  public static final int HEX = 46;
  public static final int PRINTLN = 32;
  public static final int MINUS = 20;
  public static final int CMP = 39;
  public static final int RPAREN = 13;
  public static final int NOT = 38;
  public static final int AND = 36;
  public static final int FRACTION = 48;
  public static final int OR = 37;
  public static final int COMMA = 14;
  public static final int LAZY = 4;
  public static final int CALL = 7;
  public static final int DIV = 21;
  public static final int PLUS = 19;
  public static final int IF = 40;
  public static final int ASSIGN = 9;
  public static final int EOF = 0;
  public static final int RBRACKET = 11;
  public static final int TRUE = 50;
  public static final int SIZE = 24;
  public static final int error = 1;
  public static final int MOD = 22;
  public static final int PAIR = 6;
  public static final int TIMES = 23;
  public static final int COLON = 18;
  public static final int BIN = 45;
  public static final int ELSE = 42;
  public static final int LBRACE = 15;
  public static final int BE = 8;
  public static final int READ = 33;
  public static final int LIST = 27;
  public static final int FLOAT = 47;
  public static final int LET = 43;
  public static final int THEN = 41;
  public static final int RBRACE = 16;
  public static final int IFEQUAL = 26;
  public static final int STRING = 53;
  public static final int PROC = 3;
  public static final int DEF = 2;
  public static final int FALSE = 51;
  public static final int VAR = 52;
  public static final int PRINT = 31;
}

